### ISSUE TITLE
Not working at all on Mac OS Catalina

### ISSUE THREAD

**Issue by weidmaster** [stef-k/laravel-goto-controller#18] opened 2020-10-23 12:55 UTC
I saw the extension being recommended and I gave it a try. It says to use ```ALT + Click``` to activate, but I am using Mac OS Catalina and typing ALT gives me multiple cursor and not link for the controller. I also tried the other keys, COMMAND, CONTROL and SHIFT to no avail.

I tried to find the shortcut in the shortcuts option and there is no mention of Goto Controller or anything related in the options in VSCode.

I don't know if it is because my routes files or something. I am defining routes like:
```php
Route::get('order/{id}', 'OrderController@order')->name('order');
```

**Comment by stef-k** [comment] 2020-10-23 16:18
It should be working with Cmd + click.
Does the extension underline the controllers? In your example the `OrderController@order` should be underlined.

**Comment by weidmaster** [comment] 2020-10-23 16:43
> It should be working with Cmd + click.
> Does the extension underline the controllers? In your example the `OrderController@order` should be underlined.

No it doesn't underline. The ```Route```underlines and ```post``` too but not the Controller. The screenshots shows it:

![Captura de Tela 2020-10-23 às 13 41 22](https://user-images.githubusercontent.com/9614642/97030777-acb62400-1535-11eb-8d55-25d1a2849c2e.png)
![Captura de Tela 2020-10-23 às 13 41 32](https://user-images.githubusercontent.com/9614642/97030789-b2136e80-1535-11eb-8b43-071c9520bb5f.png)
![Captura de Tela 2020-10-23 às 13 41 45](https://user-images.githubusercontent.com/9614642/97030799-b63f8c00-1535-11eb-9d4e-160d19984ebf.png)

**Comment by stef-k** [comment] 2020-10-25 08:11
as reported from @sasasa

version: 1.50.1 (system setup)
commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by stef-k** [comment] 2020-10-25 08:13
What version of the plugin do you have?

With the latest v 0.0.12, I cannot reproduce the problem on my systems:

**Win 10**
**Plugin version 0.0.12**
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Linux Ubuntu 20.04.1 LTS**
**Plugin version 0.0.12**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

![image](https://user-images.githubusercontent.com/5731388/97102247-9a122b00-16ac-11eb-8c1a-27059ffe628a.png)

![image](https://user-images.githubusercontent.com/5731388/97102033-b7de9080-16aa-11eb-8fe4-24c9f3952bad.png)

**Comment by weidmaster** [comment] 2020-10-26 12:42
@stef-k I have the same version, v.0.0.12. I tried to do a clean install of VSCode and just install this etension but it does not work either in this mac os.

I will install the extension in my Windows machine I have at home. I do use this mac in the company only.

If I can provide more debug info, I will be glad to do so.

Maybe it has to do with keybindings? I do remember some extensions have problems with keybinding on Windows and Linux because some specific function like with nVidia screens and what not. Maybe providing a way to rebind the key would make it work, as I can't find any mention of the extension in the shortcuts panel.

**Comment by stef-k** [comment] 2020-10-26 18:17
@weidmaster If you could try it on Windows that would be awesome, thanks.

**Comment by weidmaster** [comment] 2020-10-27 13:40
> @weidmaster If you could try it on Windows that would be awesome, thanks.

I found the issue! It has to do with my project not using the default folder architecture of Laravel!

I just tested it on my Windows machine and it didn't work as well. Then I remembered that the project does not follow the defaults. That is the issue! I tested in another project, with Voyager, and it works with CMD + Click, even the views!

My folder structure:
- I have the Laravel app inside /projects without a /public and /assets is separated

![Captura de Tela 2020-10-27 às 10 34 40](https://user-images.githubusercontent.com/9614642/97309080-594b1b00-1840-11eb-962a-353332135205.png)

Default Laravel structure with Voyager:
![Captura de Tela 2020-10-27 às 10 33 47](https://user-images.githubusercontent.com/9614642/97309208-7d0e6100-1840-11eb-9b66-87caad7ae378.png)

The issue is not the OS it is the folder structure. Maybe having some option to **change the project folder** for the extension would work then. I am glad I could figure it out. 

Thanks for your patience.

**Comment by stef-k** [comment] 2020-10-28 10:35
@weidmaster there is an existing setting for letting the extension know the root path of the controllers directory.
@sasasa could you please check if you have the same issue about non default project structure?

![image](https://user-images.githubusercontent.com/5731388/97424905-0fcefe80-191a-11eb-9340-31df36317c0b.png)

**Comment by weidmaster** [comment] 2020-10-28 13:09
@stef-k I didn't find this setting. I reinstalled the extension and it shows up. Yes, changing the setting to use ```/project``` does solve the problem!

We just need to remember to change it per project.

The setting should be mentioned in the README 👍 

As I can see now, what if we have Controllers in other folders as well? I think it only works for this folder only. But that is an improvement now.

Thank you!

![Captura de Tela 2020-10-28 às 09 56 15](https://user-images.githubusercontent.com/9614642/97439592-169f4680-1905-11eb-8583-14cbad2be69e.png)

![Captura de Tela 2020-10-28 às 09 55 51](https://user-images.githubusercontent.com/9614642/97439722-4bab9900-1905-11eb-8f85-c3115cf94761.png)

**Comment by stef-k** [comment] 2020-10-28 16:22
@weidmaster using multiple paths for controllers would be a good new feature. 
Unfortunately I don't have enough time to work on this.

Closing this as resolved.

**Closed as completed by stef-k** 2020-10-28 16:22 UTC
Labels: bug

**Comment by sasasa** [comment] 2020-10-29 01:13
sorry I have the same issue about non default project structure...

**Comment by stef-k** [comment] 2020-10-29 13:05
@sasasa the plugin has a setting to set the root path to the controllers directory. 

Search in settings: laravel goto controller
