### ISSUE TITLE
There seems to be conflicts with other extensions since today's update (0.0.14)

### ISSUE THREAD

**Issue by Wujidadi** [stef-k/laravel-goto-controller#26] opened 2021-09-19 11:32 UTC
This is a nice and useful extension! But ...

Since the auto-updating to v0.0.14 today, it seems that some conflicts with other extensions come out, e.g:
* Git diff doesn't work
* Markdown preview can't be displayed
* Setting sync becomes disabled
* Multiple extensions activating are pending while they are calling
* And so on ...

Little care may need be taken. Thanks!

**Comment by nagi1** [comment] 2021-09-19 13:58
Confirmed

**Comment by BNhashem16** [comment] 2021-09-19 13:58
Confirmed

**Comment by admicaa** [comment] 2021-09-19 14:49
Confirmed

**Comment by aleffelipe96** [comment] 2021-09-19 16:10
Also, I noticed that the CPU usage is very high, even closing the files it still consumes a lot of processing

**Comment by stef-k** [comment] 2021-09-19 16:29
I cannot reproduce the problems you mention here. On my system the editor seems to work just fine:

* Settings are syncing just fine by me
* Markdown renders fine

Are you sure that the issues you report here are caused by this extension? Todays changes are not that big to cause such erratic behavior. 

Can you uninstall the extension and run the tests again?

**Comment by aleffelipe96** [comment] 2021-09-19 16:40
I think it's this extension, yes, because when I disable it the CPU usage goes back to normal as it always was... and when I enable it again, the problems return

**Closed as completed** 2021-09-19 16:53 UTC

**Comment by stef-k** [comment] 2021-09-19 16:55
Falling back to 0.0.14, it should be ok now.

Report back if the issues continue
